source 'https://rubygems.org'
ruby '2.2.2'

# -----------------------
# APP FRAMEWORK & PLUGINS
# -----------------------
gem 'rails', '~> 4.2.3'

gem 'bcrypt' # enable bcrypt hashing for passwords
gem 'slim-rails'

# ------
# ASSETS
# ------
# Note that we're avoiding use of Compass, due to chronic, ongoing bugs
# https://github.com/Compass/compass-rails/issues/218
# https://github.com/Compass/compass-rails/issues/219
# https://github.com/rails/sprockets-rails/issues/210
gem 'bourbon'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'normalize-rails'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

# Pinning sprockets to avoid ActionView::Template::Error
# https://github.com/sstephenson/sprockets/issues/540
# gem 'sprockets', '2.11.0'
# gem 'sprockets-rails', '~> 2.0.0'

# ----------------
# DB and WEB STACK
# ----------------
gem 'lograge'
gem 'pg'
gem 'rails_12factor', group: [:production]
gem 'sqlite3', group: [:development]
gem 'unicorn' # use unicorn as web app server

# ------------------
# 3RD-PARTY SERVICES
# ------------------

# -----------------------------
# DEVELOPMENT AND TESTING TOOLS
# -----------------------------
group :development do
  gem 'awesome_print'
  gem 'capistrano'
  gem 'foreman'
  gem 'launchy'
  gem 'lol_dba'
  gem 'mail_safe'
  gem 'pry-rails'
  gem 'rails_best_practices'
end

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'growl'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-cucumber'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-migrate'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-mocks'
  gem 'rspec-rails', '~> 3'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

# -------
# TESTING
# -------
group :test do
  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'vcr'
  gem 'webmock'
end
